name: CI

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

# Cancel older runs for the same PR/ref so only the latest commit runs
concurrency:
  group: ci-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Tests (Python ${{ matrix.python-version }})
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Optional, but catches obvious syntax errors early
      - name: Byte-compile sources
        run: python -m compileall app function tests

      - name: Run tests
        env:
          # Ensure the repo root is importable so `app` and `function` resolve
          PYTHONPATH: ${{ github.workspace }}
        run: |
          pytest --maxfail=1 --disable-warnings
